[package]
name = "rust_bindings"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_bindings"
crate-type = ["cdylib"]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[dependencies]
pyo3 = { version = "0.16", features = ["extension-module"] }
regex = "1"
sha2 = "0.9"
