system_tick: 5

postgres:
  database: cti_breach_hunter
  user: cti_user
  password: cti_password
  host: localhost
  port: 5432

elasticsearch:
  host: localhost
  port: 9200
  scheme: http
  user: elastic
  password: elastic

kafka:
  bootstrap_servers: localhost:9092
  topic: scrap_topic
  notification_topic: processed_topic

processing: true
collecting: true

smb_servers:
  - name: smb_server_1
    share: //smb-server1/scraps
    username: smbuser1
    password: smbpassword1
    mount_point: /mnt/smb_scraps1

upstream_smb:
  name: smb_server_1
  share: //smb-server1/scraps
  username: smbuser1
  password: smbpassword1
  mount_point: /mnt/smb_scraps1
